
title: Open Source Commerce .DEV
email: info@scale.sc
description: >-
  Developing free software that solves common challenges for e-commerce businesses. 
  Funded by companies and individuals who want to build a better internet and an 
  open e-commerce community.
baseurl: "/" 
url: "https://osc.dev"
#twitter_username:
github_username:  osc-dev

plugins: []

exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - _site
  - .gitignore
  - docker-compose.yml

sass:
  sourcemap: never

collections:
  - sections